services:
  phoenixd:
    image: acinq/phoenixd:latest
    container_name: phoenixd
    restart: unless-stopped
    networks:
      - default
    ports:
      - "9740:9740"
    volumes:
      - phoenixd_datadir:/phoenix/.phoenix 

  ambrosia:
    build: server/
    image: ambrosia
    container_name: ambrosia
    restart: unless-stopped
    networks:
      - default
    ports:
      - "9154:9154"
      - "9443:9443"
    volumes:
      - ambrosia_datadir:/root/.Ambrosia-POS
      - phoenixd_datadir:/root/.phoenix  
    depends_on:
      - phoenixd

  ambrosia-client:
    build: client/
    image: ambrosia-client
    container_name: ambrosia-client
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ambrosia_datadir:/root/.Ambrosia-POS
    depends_on:
      - ambrosia
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://ambrosia:9154
      NEXT_PUBLIC_WS_URL: ws://localhost:9154/ws/payments

volumes:
  phoenixd_datadir: 
  ambrosia_datadir:
